### ISSUE TITLE
Enable blinking cursor before text is printed with delay

### ISSUE THREAD

**Issue by Slluxx** [khushit-shah/WriteIt.js#11]
Adding delay shows the cursor but its not blinking. It doesnt look like an input is or can be made but more like the letter I. How can that be fixed?

**Comment by khushit-shah** [comment]
Hi!, Thanks for the issue, I can't work on it right now as I have a major exam coming up! I can work on it after 1st week of Feb,
If you want you can look at the code,  
https://github.com/khushit-shah/WriteIt.js/blob/571a7d83c7a2742e89e277d20d839e0c95788f93/WriteIt.js#L304-L308

Here you can plug a similar mechanism like the following.
https://github.com/khushit-shah/WriteIt.js/blob/571a7d83c7a2742e89e277d20d839e0c95788f93/WriteIt.js#L564-L572


You can also change the cursor with `writeit-char` 
[doc here](https://khushit-shah.github.io/WriteIt.js/#:~:text=WriteItJS.startAnimation()%3C/script%3E-,%23%20writeit%2Dchar,-It%20defines%20the)

**Comment by khushit-shah** [comment]
Hii can you check that the problem has been fixed?
