### ISSUE TITLE
Write, wait, delete, write again.

### ISSUE THREAD

**Issue by umitseyhan75** [khushit-shah/WriteIt.js#9]
Is it possible to do this: write "one", wait 3 seconds, delete "one", wait 1 seconds,  write "two", wait 3 seconds, delete "two", wait 1 seconds, write "three", wait 3 seconds, delete "three", wait 1 seconds, start from the beginning again (loop).

**Comment by khushit-shah** [comment]
Yess! You can use writeit-loop-reverse with writeit-replace-next
<p writeit-replace-next="one ${3}, ${1} two ${3}, ${1} three ${3}, ${1}"></p>

**Comment by umitseyhan75** [comment]
Ok, what is missing [here](https://codepen.io/umitseyhan/pen/jOpEVQr)?

**Comment by khushit-shah** [comment]
There seems to be a bug! ${x} and writeit-loop-reverse is not working. I am looking into it!

**Comment by khushit-shah** [comment]
added hotfix! use the new WriteIt.js file with the following code

`<p writeit-autostart writeit-animate writeit-loop-reverse writeit-replace-next="one ${1}, ${1} two${3} , ${1} three ${30}, ${1}"></p>`

**Comment by umitseyhan75** [comment]
I've observed two problems with the new code. Can be checked [here](https://codepen.io/umitseyhan/pen/jOpEVQr).
1- When text deleted, the entire element gets removed so the other elements around it moves to fill the empty space.
2- Blink animation stops working after the typing done.

Uploading k1cvdWKVXE.mp4…

**Comment by khushit-shah** [comment]
Thanks for sharing! this is surely a bug, will fix it as soon as possible.

**Comment by khushit-shah** [comment]
Hi, As per the design I have made, there is no blinking cursor when waiting. Is it better to have a blinking cursor there? 
Also we can use `&nbsp;` to stop from other elements moving around

**Comment by khushit-shah** [comment]
can you check that it is working as expected?

**Comment by umitseyhan75** [comment]
All looking good! But is it possible to make it read the content of the `<p>` instead of taking it from attribute values as the current situation is not really accessibility friendly?

**Comment by khushit-shah** [comment]
Right now it is not possible to do this, I can add this functionality. I will create a separate issue for this.
